[package]
name = "local_net"
version = "0.1.0"
edition = "2021"
authors = [ "Lukas (LukyLuke_ch) Zurschmiede <network-discover@ranta.ch>" ]

[lib]
name = "local_net"
path = "src/lib.rs"

[dependencies]
config = { path = "../config" }

log = { version = "0.*" }
