[package]
name = "network"
version = "0.1.0"
edition = "2021"
authors = [ "Lukas (LukyLuke_ch) Zurschmiede <network-discover@ranta.ch>" ]

[lib]
name = "network"
path = "src/lib.rs"

[dependencies]
local_net = { path = "../local_net" }

log = { version = "0.4" }
roxmltree = { version = "0.14.1" }

