#!/bin/sh

NAME=`basename $0`
_DIR="/opt/network_discover/"

if [ "$#" != "2" ]; then
  echo "$0 start|stop scanner|webui"
  exit 1
fi

_RUN=/var/run/${NAME}_${2}.run
if [ -f ${_RUN} -a "${1}" == "start" ]; then
  ps -p $( cat ${_RUN} ) 1>/dev/null 2>&1
  if [ "$?" != "1" ]; then
    echo "$0 $2 already running"
    exit 2
  fi
fi

echo "$$" > ${_RUN}

start_scanner() {
  cd $_DIR
  /usr/bin/python3 discover.py
}
start_webui() {
  cd $_DIR
  /usr/bin/python3 server.py
}

stop() {
  kill -9 $( cat ${_RUN} ) 1>/dev/null 2>&1
}

case "$1" in
  start) "${1}_${2}" ;;
  stop) stop ;;
esac

rm ${_RUN} &>/dev/null
